
<% branch_name = `git rev-parse --abbrev-ref HEAD`.strip %>

<% case branch_name ;
   when 'master'      %>
<% puts "no app config defined for this branch" %>
<% when 'tip4commit' %>
github:
  key: "111111111111"
  secret: "111111111111"
  auto_paginate: false
  pages: 3
  project_pages:
    "torvalds/linux": 30

blockchain_info:
  guid: "111111111111"
  password: "111111111111"
  callback_secret: "111111111111"

tip:        0.01
min_payout: 100000
our_fee:    0.05

deposit_address: 1M4bS4gPyA6Kb8w7aXsgth9oUZWcRk73tQ

address_versions: # 0/5 for bitcoin addresses, 111/196 for testnet, see chainparams.cpp
  - 0
  - 5


<% when 'peer4commit' %>
github:
  key: "111111111111"
  secret: "111111111111"

daemon:
  username: rpcuser
  password: rpcpassword
  host: localhost
  port: 9904
  path: /path/to/ppcoin/src/ppcoind

tip:          0.01
min_payout:   1.0 # in PPC
our_fee:      0.05
tipper_delay: "1.hour"

address_versions: # 55/117 for peercoin, 111/196 for testnet, see base58.h
  - 111
  - 196

# canonical_host: peer4commit.example.com # will redirect all other hostnames to this one


<% when 'prime4commit' %>
github:
  key: "111111111111"
  secret: "111111111111"

daemon:
  username: rpcuser
  password: rpcpassword
  host: localhost
  port: 9914
  path: /path/to/primecoin/src/primecoind

tip:          0.01
min_payout:   1.0 # in XPM
our_fee:      0.05
tipper_delay: "1.hour"

address_versions: # 23/83 for primecoin, 111/196 for testnet, see base58.h
  - 111
  - 196

# canonical_host: prime4commit.example.com # will redirect all other hostnames to this one


<% else %>
<% puts "no app config defined for this branch" %>
<% end %>


devise:
  secret: "111111111111"

application:
  secret: "111111111111"

smtp_settings:
  address:              smtp.gmail.com
  port:                 587
  domain:               foobar.com
  user_name:            example@foobar.com
  password:             MY_PASSWORD
  authentication:       plain
  enable_starttls_auto: true

# Uncomment to use airbrake/errbit

# airbrake:
#   api_key: 111111111111
#   host: errbit.tip4commit.com

